SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `cgraphz`.`perm_module` ADD COLUMN `menu_name` VARCHAR(45) NULL DEFAULT NULL  AFTER `component` , ADD COLUMN `menu_order` INT(11) NULL DEFAULT NULL  AFTER `menu_name` ;

ALTER TABLE `cgraphz`.`config_plugin_filter` ADD COLUMN `plugin_order` INT(11) NULL DEFAULT NULL  AFTER `plugin_filter_desc` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
